### ISSUE TITLE
tmuxp fails after update of Colorama from 0.3.9 to 0.4.0-1 on Arch Linux

### ISSUE THREAD

**Issue by Phantas0s** [tmux-python/tmuxp#445]
tmuxp fails after I updated my Arch Linux install because of a new version of python-colorama (I believe)

The version on my machine is: python-colorama 0.4.0-1

Here the error message: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (colorama 0.4.0 (/usr/lib/python3.7/site-packages), Requirement.parse('colorama==0.3.9'), {'tmuxp'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmuxp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'colorama==0.3.9' distribution was not found and is required by tmuxp
```

**Comment by dvzrv** [comment]
I have [removed the version pinning](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/tmuxp&id=a0cbc3ea0fa3f2ac354bbb25a072484592619b0d) for the package before build.

**Comment by rfoliva** [comment]
@Phantas0s - Thanks for raising this. We are working with @dvzrv who is the package maintainer for tmuxp (Arch distro). He has already put in an interim solution for his package and we will be addressing this on our side, in hopes this is no longer needed and does not happen again.

As such, can we close this issue and continue to work on this via #432 ?

Please let me know.

Thanks,
Ricardo

**Comment by Phantas0s** [comment]
@rfoliva Yes sure. I close the issue now. Thanks for the quick fix!

**Comment by rfoliva** [comment]
Thanks @Phantas0s , but the credit goes to @dvzrv on this one. ;)
