### ISSUE TITLE
tmux version "next-2.9": TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by kaushalmodi** [tmux-python/tmuxp#449]
Hello,

One of the 2 upgrades (python or tmux) broke `tmuxp` for me:

- tmux next-2.9 (using the latest tmux built from master as of today)
- Python 3.7.0

I uninstalled and reinstalled tmuxp using:

```
pip3 uninstall tmuxp
pip3 install --user tmuxp
```

But when I try to load a tmuxp config (as I always do, and worked), by doing `tmuxp load servers -d`, I get:

```
Traceback (most recent call last):
  File "/home/kmodi/.local/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.4.2', 'console_scripts', 'tmuxp')()
  File "/home/kmodi/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kmodi/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kmodi/.local/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/kmodi/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kmodi/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kmodi/.local/lib/python3.7/site-packages/tmuxp/cli.py", line 403, in cli
    has_minimum_version()
  File "/home/kmodi/.local/lib/python3.7/site-packages/libtmux/common.py", line 514, in has_minimum_version
    if get_version() < LooseVersion(TMUX_MIN_VERSION):
  File "/home/kmodi/stow/pkgs/python/3.7.0/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/home/kmodi/stow/pkgs/python/3.7.0/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by kaushalmodi** [comment]
Maybe tmuxp doesn't like the new non-int version string of tmux? https://github.com/tmux/tmux/commit/bc6211cca5b06714ea2e57f247cd98b509a441c1

**Comment by kaushalmodi** [comment]
I confirm this bug in tmuxp. After I reverted that specific commit in tmux, and rebuilt it, tmuxp works fine.

**Comment by sloria** [comment]
I also ran into this using the tmux `next-2.9` (the latest Homebrew release). The issue is in libtmux. I sent a PR https://github.com/tmux-python/libtmux/pull/172 and verified that it works .

**Comment by tony** [comment]
@kaushalmodi @sloria I'm going to tag a release this weekend. Maybe sooner.

**Comment by tony** [comment]
@kaushalmodi @sloria and anyone who reads this, tmux-python is looking for help: #290
