### ISSUE TITLE
tmux 3.0 makes layout break

### ISSUE THREAD

**Issue by synthmeat** [tmux-python/tmuxp#514]
### Step 1: Provide a summary of your problem
With new tmux, `layout` property crashes tmuxp.

### Step 2: Provide tmuxp details
  * Python version
`3.7.5`
  * system PATH 
`/Users/synthmeat/.cargo/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/usr/local/git/bin:/usr/local/opt/ruby/bin:/Users/synthmeat/Library/Python/3.7/bin:/Users/synthmeat/.gopath/bin:/usr/local/opt/go/libexec/bin:/Users/synthmeat/.pub-cache/bin:/Users/synthmeat/.scripts:/Users/synthmeat/.local/bin`
  * tmux version
`3.0`
  * tmuxp version
`1.5.4`
  * tmux path
`/usr/local/bin/tmux`
  * tmuxp path
`/Users/synthmeat/Library/Python/3.7/bin/tmuxp`
  * libtmux version
`0.8.1`
  * shell
`GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)`
  * output of `tmux list-sessions`, `tmux list-windows`, `tmux list-panes`
`N/A`
  * output of `tmux show-options -g`, `tmux show-window-options -g`
`N/A`
  * output of `tmuxp freeze <SESSION_NAME>`
`N/A`

### Step 3: Describe your environment
  * Architecture: `x86_64`
  * OS version: `macOS 10.15.1`

#### Steps to reproduce:
  1. create configuration like
```yaml
session_name: repro
start_directory: ~

windows:

- window_name: window
  layout: 53f3,248x55,0,0{139x55,0,0,3,108x55,140,0,4}
  panes:
  - shell_command:
    - ls
  - shell_command:
    - ls
```
  2. `tmuxp load repro`

#### Observed Results:
  It crashes with:
```
Traceback (most recent call last):
  File "/Users/synthmeat/Library/Python/3.7/bin/tmuxp", line 8, in <module>
    sys.exit(cli.cli())
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/tmuxp/cli.py", line 814, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/tmuxp/cli.py", line 498, in load_workspace
    sconfig = config.expand(sconfig, os.path.dirname(config_file))
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/tmuxp/config.py", line 240, in expand
    sconf['start_directory'] = expandshell(sconf['start_directory'])
  File "/Users/synthmeat/Library/Python/3.7/lib/python/site-packages/tmuxp/config.py", line 129, in expandshell
    return os.path.expandvars(os.path.expanduser(_path))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

#### Expected Results:
  For it to not crash. :)

#### Relevant Code:
  See above.

**Comment by egbloom** [comment]
For me, the error is
``` File "/Users/bloom/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 315, in iter_create_panes
    w.select_layout(wconf['layout'])
  File "/Users/bloom/.pyenv/versions/3.8.0/lib/python3.8/site-packages/libtmux/window.py", line 151, in select_layout
    raise exc.LibTmuxException(proc.stderr)```

if i remove the "layout" keys from the json file, then tmux loads. perhaps this is related to the following changes in 3.0:
```* INCOMPATIBLE: Add a new {} syntax to the configuration file. This is a string
  similar to single quotes but also includes newlines and allows commands that
  take other commands as string arguments to be expressed more clearly and
  without additional escaping.```

**Comment by synthmeat** [comment]
For posterity, tmux 3.0a fixes this. 🥳

Thanks you for the awesome tool.
