### ISSUE TITLE
Load with layout field fails.

### ISSUE THREAD

**Issue by deliciouslytyped** [tmux-python/tmuxp#531]
Per, https://github.com/tmux-python/tmuxp/issues/522#issuecomment-568910555

After some quick fiddling, removing the layout field prevents the crash.
My current hypothesis is that something (I need to check / see tmux 3 changelog) changed in the layout format in the tmux 3 update but I haven't confirmed yet with an older version.

repasted error:
```
$ tmuxp load -S ./socket 3.json
[Loading] /run/user/1000/tmp.kSvepSlq6I/3.json
Traceback (most recent call last):
  File "/nix/store/hnnz9g0kswahg630b4rwxh00l8bw2pmd-tmuxp-1.5.4/bin/.tmuxp-wrapped", line 9, in <module>
    sys.exit(cli.cli())
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/lma5qkl6r8vqrbhs7w202fxbrxd1c7fa-python3.7-click-7.0/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/hnnz9g0kswahg630b4rwxh00l8bw2pmd-tmuxp-1.5.4/lib/python3.7/site-packages/tmuxp/cli.py", line 814, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/nix/store/hnnz9g0kswahg630b4rwxh00l8bw2pmd-tmuxp-1.5.4/lib/python3.7/site-packages/tmuxp/cli.py", line 536, in load_workspace
    builder.build()  # load tmux session via workspace builder
  File "/nix/store/hnnz9g0kswahg630b4rwxh00l8bw2pmd-tmuxp-1.5.4/lib/python3.7/site-packages/tmuxp/workspacebuilder.py", line 184, in build
    for p, pconf in self.iter_create_panes(w, wconf):
  File "/nix/store/hnnz9g0kswahg630b4rwxh00l8bw2pmd-tmuxp-1.5.4/lib/python3.7/site-packages/tmuxp/workspacebuilder.py", line 315, in iter_create_panes
    w.select_layout(wconf['layout'])
  File "/nix/store/khrmcyr697xxwi1f616q7w8frskbw1sx-python3.7-libtmux-0.8.2/lib/python3.7/site-packages/libtmux/window.py", line 151, in select_layout
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['server exited unexpectedly']
```

Repasted config:
```json
{
  "session_name": "0",
  "windows": [
    {      
      "options": {},
      "window_name": "bash",
      "layout": "f72d,271x66,0,0[271x33,0,0,31,271x32,0,34,35]",
      "panes": [
        {
          "shell_command": "bash",
          "focus": "true"
        },
        "nix"
      ],
      "start_directory": "/"
    }
  ]  
}
```

Removing the `"layout"`` field avoids the crash.

**Comment by deliciouslytyped** [comment]
It's probably not a format change because tmux complains if you input an invalid format.

**Comment by deliciouslytyped** [comment]
I did have trouble at some point while using tmuxinator where layout creation in the detached buffer was failing for some reason but I don't remember the details. There may have been two cases there, one of which was the creation failing if the virtual screen size was too small, but I believe that had it's own error, not just a general failure.

I'm not sure how to debug this properly right now.

**Comment by deliciouslytyped** [comment]
Looks like either a misunderstanding about how to use this, or an upstream bug.

repro:
```
$ tmux -S ./socket new-session -x 600 -y 800 -d
$ tmux -S ./socket select-layout "f72d,271x66,0,0[271x33,0,0,31,271x32,0,34,35]"
server exited unexpectedly
```

upstream at https://github.com/tmux/tmux/issues/2035

**Comment by deliciouslytyped** [comment]
It seems to be solved by updating from slightly outdated 3.0 build to 3.0a .

**Comment by deliciouslytyped** [comment]
Wow tmuxp is actually pretty neat.

**Comment by tony** [comment]
@deliciouslytyped did you get resurrect working with tmuxp?
