### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by gavinhoward** [tmux-python/tmuxp#547]
### Step 1: Provide a summary of your problem
When attempting to use `tmuxp`, I get the following error:

```
TypeError: 'NoneType' object is not subscriptable
```

### Step 2: Provide tmuxp details
  * Python version: 3.8
  * system PATH: `/home/gavin/.anaconda3/bin:/home/gavin/.local/bin:/home/gavin/.coverity/bin:/usr/local/go/bin:/home/gavin/Code/Go/bin:/home/gavin/.gem/ruby/2.7.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  * tmux version: 3.0a
  * tmuxp version: 1.5.4
  * tmux path: `/usr/bin/tmux`
  * tmuxp path: `/usr/bin/tmuxp`
  * libtmux version: Whatever version is in tmuxp 1.5.4
  * shell: bash 5.0.16
  * output of `tmux list-sessions`:

```
0: 1 windows (created Tue Feb 18 15:40:28 2020) (attached)
```

  * output of `tmux list-windows`:

```
0: bash* (1 panes) [382x112] [layout 8e0d,382x112,0,0,0] @0 (active)
```

  * output of `tmux list-panes`:

```
0: [382x112] [history 109/100000, 77064 bytes] %0 (active)
```

  * output of `tmux show-options -g`:

```
@emulate-scroll-for-no-mouse-alternate-buffer on
@plugin tmux-plugins/tmux-logging
@prefix_highlight_copy_prompt Copy
@prefix_highlight_empty_attr fg=default,bg=green
@prefix_highlight_empty_has_affixes off
@prefix_highlight_output_prefix "< "
@prefix_highlight_output_suffix " >"
@prefix_highlight_prefix_prompt Wait
@prefix_highlight_show_copy_mode on
@prefix_highlight_show_sync_mode on
@prefix_highlight_sync_prompt Sync
@yank_selection clipboard
activity-action other
assume-paste-time 1
base-index 0
bell-action any
default-command 
default-shell /bin/bash
default-size 80x24
destroy-unattached off
detach-on-destroy on
display-panes-active-colour red
display-panes-colour blue
display-panes-time 1000
display-time 4000
history-limit 100000
key-table root
lock-after-time 0
lock-command "lock -np"
message-command-style fg=yellow,bg=black
message-style fg=black,bg=yellow
mouse on
prefix C-v
prefix2 None
renumber-windows off
repeat-time 500
set-titles on
set-titles-string "#S / #W"
silence-action other
status on
status-bg green
status-fg black
status-format[0] "#[align=left range=left #{status-left-style}]#{T;=/#{status-left-length}:status-left}#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{window-status-style}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#{T:window-status-format}#[norange default]#{?window_end_flag,,#{window-status-separator}},#[range=window|#{window_index} list=focus #{?#{!=:#{window-status-current-style},default},#{window-status-current-style},#{window-status-style}}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#{T:window-status-current-format}#[norange list=on default]#{?window_end_flag,,#{window-status-separator}}}#[nolist align=right range=right #{status-right-style}]#{T;=/#{status-right-length}:status-right}#[norange default]"
status-format[1] "#[align=centre]#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_width}x#{pane_height}]#[default] }"
status-interval 1
status-justify centre
status-keys emacs
status-left "#[fg=colour231,bg=colour04]#{?client_prefix,< Wait >,}#[default,fg=default,bg=yellow]#{?pane_in_mode,< Copy >,}#[default,fg=default,bg=yellow]#{?synchronize-panes,< Sync >,}#[default]"
status-left-length 15
status-left-style default
status-position bottom
status-right "Online: #(/home/gavin/.tmux/plugins/tmux-online-status/scripts/online_status_icon.sh) | %a, %h %d | %H:%M:%S "
status-right-length 40
status-right-style default
status-style fg=black,bg=green
update-environment[0] DISPLAY
update-environment[1] KRB5CCNAME
update-environment[2] SSH_ASKPASS
update-environment[3] SSH_AUTH_SOCK
update-environment[4] SSH_AGENT_PID
update-environment[5] SSH_CONNECTION
update-environment[6] WINDOWID
update-environment[7] XAUTHORITY
visual-activity off
visual-bell off
visual-silence off
word-separators " "
```

  * output of `tmux show-window-options -g`:

```
aggressive-resize on
allow-rename off
alternate-screen on
automatic-rename on
automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}"
clock-mode-colour blue
clock-mode-style 24
main-pane-height 24
main-pane-width 80
mode-keys vi
mode-style fg=black,bg=yellow
monitor-activity off
monitor-bell on
monitor-silence 0
other-pane-height 0
other-pane-width 0
pane-active-border-style fg=green
pane-base-index 0
pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] \"#{pane_title}\""
pane-border-status off
pane-border-style default
remain-on-exit off
synchronize-panes off
window-active-style default
window-size smallest
window-style default
window-status-activity-style reverse
window-status-bell-style reverse
window-status-current-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-current-style default
window-status-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-last-style default
window-status-separator " "
window-status-style default
wrap-search on
xterm-keys on
```

  * output of `tmuxp freeze <SESSION_NAME>`:

```
Session not found.
```

### Step 3: Describe your environment
  * Architecture: `x86_64`
  * OS version: Arch Linux, updated (Linux 5.5)

#### Steps to reproduce:
  1. Open `gnome-terminal` in fullscreen.
  2. Start `tmux`.
  3. Run `tmuxp load bc` (file is in `~/.tmuxp/`).

#### Observed Results:
I get the following traceback:

```
(E) [16:02:58] libtmux.session session._info():82 list index out of range
Traceback (most recent call last):
  File "/usr/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.5.4', 'console_scripts', 'tmuxp')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmuxp/cli.py", line 814, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/lib/python3.8/site-packages/tmuxp/cli.py", line 536, in load_workspace
    builder.build()  # load tmux session via workspace builder
  File "/usr/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 180, in build
    for w, wconf in self.iter_create_windows(session):
  File "/usr/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 247, in iter_create_windows
    w = s.new_window(
  File "/usr/lib/python3.8/site-packages/libtmux/session.py", line 231, in new_window
    % (self.id, window_index),
  File "/usr/lib/python3.8/site-packages/libtmux/common.py", line 277, in __getattr__
    return self._info[self.formatter_prefix + key]
TypeError: 'NoneType' object is not subscriptable
```

#### Expected Results:
I expected the configuration pasted below to work. I also fully understand that this problem is probably my fault, but I am new to `tmuxp`.

#### Relevant Code:
```
session_name: bc
start_directory: /home/gavin/Code/Tools/bc-git/bc

windows:
  - window_name: editor
    layout: main-vertical
    panes:
      - vim
  - window_name: terminal
    layout: main-vertical
    panes:
      -
      -
  - window_name: debug
    layout: main-vertical
    panes:
      - vim
      - setupgdb
```

**Comment by gavinhoward** [comment]
Just a note: the above traceback is when I run the command inside a `tmux` session. If I run the same things outside, I get the following traceback:

```
[Loading] /home/gavin/.tmuxp/bc.yaml
Traceback (most recent call last):
  File "/usr/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.5.4', 'console_scripts', 'tmuxp')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmuxp/cli.py", line 814, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/lib/python3.8/site-packages/tmuxp/cli.py", line 536, in load_workspace
    builder.build()  # load tmux session via workspace builder
  File "/usr/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 180, in build
    for w, wconf in self.iter_create_windows(session):
  File "/usr/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 256, in iter_create_windows
    w1.kill_window()
  File "/usr/lib/python3.8/site-packages/libtmux/window.py", line 314, in kill_window
    self.server._update_windows()
  File "/usr/lib/python3.8/site-packages/libtmux/server.py", line 249, in _update_windows
    self._list_windows()
  File "/usr/lib/python3.8/site-packages/libtmux/server.py", line 217, in _list_windows
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['no current target']
```

**Comment by gavinhoward** [comment]
After looking at various issues on this project, it seems this project is not maintained much anymore, so I will close this bug.

**Comment by sloria** [comment]
I was also getting this error after upgrading tmux and ncurses with Homebrew. The root cause was an issue in tmux, and the fix here https://github.com/tmux/tmux/issues/743#issuecomment-581499838 worked for me.

**Comment by zachwill** [comment]
For anyone coming across this from Google, [this is the best solution](https://github.com/tmux/tmux/issues/743#issuecomment-581499838).

```
cd /tmp
rm -rf tmux*
```

Afterwards, everything should work fine. (The real bug is with `homebrew` updating `ncurses` behind the scenes.)
