### ISSUE TITLE
I install it from pip and when i tried to use load cmd it shows error below.

### ISSUE THREAD

**Issue by coderj001** [tmux-python/tmuxp#622]
Traceback (most recent call last):
  File "/home/user/.local/bin/tmuxp", line 8, in <module>
    sys.exit(cli.cli())
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tmuxp/cli.py", line 816, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/home/user/.local/lib/python3.8/site-packages/tmuxp/cli.py", line 538, in load_workspace
    builder.build()  # load tmux session via workspace builder
  File "/home/user/.local/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 180, in build
    for w, wconf in self.iter_create_windows(session):
  File "/home/user/.local/lib/python3.8/site-packages/tmuxp/workspacebuilder.py", line 247, in iter_create_windows
    w = s.new_window(
  File "/home/user/.local/lib/python3.8/site-packages/libtmux/session.py", line 240, in new_window
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['no current client']

**Comment by joseph-flinn** [comment]
Can you provide some more information for context?

1. OS Name and Version
2. Version of Python using
3. Version of `tmux` installed
4. Version of `tmuxp` installed
5. The exact command you are running to produce the above output

**Comment by coderj001** [comment]
So debugged it and found out the problem was with tmux extension which I have installed at that time. Now it works fine, thank you for the reply.
