### ISSUE TITLE
Fresh install, doesn't work for sample yaml

### ISSUE THREAD

**Issue by depesz** [tmux-python/tmuxp#775]
### Step 1: Provide a summary of your problem

Installed tmuxp using pip3:

```
=$ pip3 install tmuxp
Defaulting to user installation because normal site-packages is not writeable
Collecting tmuxp
  Downloading tmuxp-1.11.0-py3-none-any.whl (38 kB)
Collecting kaptan>=0.5.10
  Downloading kaptan-0.5.12.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click<8.2,>7 in /usr/lib/python3/dist-packages (from tmuxp) (7.1.2)
Requirement already satisfied: colorama>=0.3.9 in ./.local/lib/python3.9/site-packages (from tmuxp) (0.4.3)
Collecting libtmux<0.12.0,>=0.11.0
  Downloading libtmux-0.11.0-py3-none-any.whl (28 kB)
Requirement already satisfied: PyYAML<6,>=3.13 in /usr/lib/python3/dist-packages (from kaptan>=0.5.10->tmuxp) (5.3.1)
Building wheels for collected packages: kaptan
  Building wheel for kaptan (setup.py) ... done
  Created wheel for kaptan: filename=kaptan-0.5.12-py3-none-any.whl size=10974 sha256=36cba627f8018cc83b5219d0b8b3be7a6e03b7ae62ff37986fe3a2d4f04832a9
  Stored in directory: /mnt/storage/depesz/.cache/pip/wheels/81/12/bc/764c239aab3a42a68c7b7f5e87b9b72129dbf35e2548f0b0e5
Successfully built kaptan
Installing collected packages: libtmux, kaptan, tmuxp
Successfully installed kaptan-0.5.12 libtmux-0.11.0 tmuxp-1.11.0
```

copy-pasted mysession.yaml from your readme, and tried to load it:

```
=$ tmuxp load mysession.yaml
Traceback (most recent call last):
  File "/home/depesz/.local/bin/tmuxp", line 5, in <module>
    from tmuxp import cli
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/__init__.py", line 11, in <module>
    from . import cli, config, util
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/cli/__init__.py", line 24, in <module>
    from .freeze import command_freeze
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/cli/freeze.py", line 51, in <module>
    def command_freeze(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 168, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1984, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'
```

### Step 2: Provide tmuxp details

```
=$ tmuxp debug-info
Traceback (most recent call last):
  File "/home/depesz/.local/bin/tmuxp", line 5, in <module>
    from tmuxp import cli
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/__init__.py", line 11, in <module>
    from . import cli, config, util
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/cli/__init__.py", line 24, in <module>
    from .freeze import command_freeze
  File "/home/depesz/.local/lib/python3.9/site-packages/tmuxp/cli/freeze.py", line 51, in <module>
    def command_freeze(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 168, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1984, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'
```

As for other things. I'm on ubuntu 21.10 (impish) with python3 v. 3.9.4-1build1. tmux from apt in version 3.1c

#### Steps to reproduce:
  1. pip3 install tmuxp
  2. tmuxp load mysession.yaml

#### Observed Results:
  * Immediate error

#### Expected Results:
  * Well, I would expect it to work. Make a tmux session perhaps?

#### Relevant Code:
  ```
session_name: 4-pane-split
windows:
  - window_name: dev window
    layout: tiled
    shell_command_before:
      - cd ~/ # run as a first command in all panes
    panes:
      - shell_command: # pane no. 1
          - cd /var/log # run multiple commands in this pane
          - ls -al | grep \.log
      - echo second pane # pane no. 2
      - echo third pane # pane no. 3
      - echo forth pane # pane no. 4
```

**Comment by tony** [comment]
@depesz I was able to get this to load.

```
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 168, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1984, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'
```

`pip show click` ?

**Comment by depesz** [comment]
```
=$ pip show click
Name: click
Version: 7.1.2
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: 
Author-email: 
License: BSD-3-Clause
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: pgcli, pgspecial, tmuxp
```

Did `pip install -U click` (got version 8.1.3) and now it works.

**Comment by tony** [comment]
thank you for filing this issue

I believe this is a mistake of mine.  tmuxp 1.11.0 needs [click 8.0.0](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0) but I didn't set the dependency

I am going to make a patch for this

**Comment by depesz** [comment]
Great. Thank you very much for quick response, and help. Closing the ticket, as it's solved :)

**Comment by tony** [comment]
tmuxp v1.11.1 should fix this in future cases

- https://pypi.org/project/tmuxp/1.11.1/
- https://github.com/tmux-python/tmuxp/blob/v1.11.1/CHANGES
- https://github.com/tmux-python/tmuxp/tree/v1.11.1
